### ISSUE TITLE
String 6017

### ISSUE THREAD

**Issue by JoelTroch** [OpenRCT2/Localisation#1015]
New strings from PR OpenRCT2/OpenRCT2#5202.

```
STR_6017    :Please slow down
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES

**Comment by afk** [comment]
I would translate this to de-DE, so this issue could be closed, but I'm missing the context where the string is used. Can anyone explain what is meant by `Please slow down`?

**Comment by Gymnasiast** [comment]
@afk You can click on the link in the first post to see what added this string.

In this case: code was added to prevent a player in a network game from demolishing everything. If you try to demolish things too quickly, the game will block it and display "Please slow down".
