### ISSUE TITLE
String 5430

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/Localisation#1146]
New strings from PR OpenRCT2/OpenRCT2/pull/5755

Title sequence wait periods are no longer determined in seconds but now in milliseconds.

```
STR_5430   : Time in milliseconds
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES

**Comment by octaroot** [comment]
I'm confused. The PR you linked is from this repository, not the main game. Also and you are changing STR_5424.

**Comment by spacek531** [comment]
sorry, this is my first time.

**Comment by Nubbie** [comment]
@spacek531 
**Note**: Wrong string-id, the correct one is 
``STR_5430    :Milliseconds to wait:``
Also change the title to ``String 5430``, then It's good 😄

**Comment by spacek531** [comment]
haha 5424 was the string I had to change to use UINT8, sorry about that

**Comment by octaroot** [comment]
@spacek531 Oh, I see, right!
btw the title of this PR is still wrong :D it's 5430 not 5340, but that's just me being mean :-)

**Comment by Nubbie** [comment]
@Gymnasiast Accidentally closed
