### ISSUE TITLE
Strings 6131, 6132-6133

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/Localisation#1162]
New strings from PR OpenRCT2/OpenRCT2#5869 and OpenRCT2/OpenRCT2#5815.

```
STR_6131    :Object source
```

```
STR_6132    :Ignore research status
STR_6133    :{SMALLFONT}{BLACK}Access rides and scenery that have not yet been invented
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES

**Comment by Nubbie** [comment]
@daihakkeni @Wirlie zh-TW & es-ES haven't applied

**Comment by daihakken** [comment]
@Nubble already applied on Aug 11 with PR #1194 (3ac81ac).
