### ISSUE TITLE
Track designer strings

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#1168]
Changed strings from PR OpenRCT2/OpenRCT2#5991.

```
STR_0888    :Quit Track Designer
STR_3207    :Track Designer
STR_3335    :Track Designer - Select Ride Types & Vehicles
STR_3344    :Track Designer
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES

**Comment by JoelTroch** [comment]
@Gymnasiast Already done for fr-FR

**Comment by Nubbie** [comment]
[ zhTW have applied ](https://github.com/OpenRCT2/Localisation/commit/f702d42719b119e40bbaba4979a79ce3fbf97869#diff-836f39ea934cec0e858c8d9ddf701d75R893)

**Comment by Gymnasiast** [comment]
@J0anJosep

**Comment by Gymnasiast** [comment]
(Not actually applied in Catalan yet.)
