### ISSUE TITLE
Some notes about the Brazilian Portuguese 

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#123]
As written by @kaudy, who provided the first version.

I'm working on the translation for Brazilian Portuguese.

-The Translation is currently 55%
-All Translations with "*" must be re-calibrated.

Estou trabalhando na tradução para o português brasileiro. Eu criei esse tópico para discutirmos sobre os termos usados na tradução.

-A tradução está atualmente em 55%
-Todas as traduções com "*" precisam ser novamente verificadas.

**Comment by kaudy** [comment]
tks @Gymnasiast, I'm reworking the translation and making compatible with the version uk
