### ISSUE TITLE
String 5157, 6148-6153

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#1245]
New strings from PR OpenRCT2/OpenRCT2#6433 and OpenRCT2/OpenRCT2#6375.

```
STR_5157    :<removed string - do not use>
STR_6148    :Connecting to master server...
STR_6149    :Unable to connect to master server
STR_6150    :Invalid response from master server (no JSON number)
STR_6151    :Master server failed to return servers
STR_6152    :Invalid response from master server (no JSON array)
STR_6153    :Pay to enter park / Pay per ride
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES
- [x] ja-JP

Notification when new strings arrive:
@Nubbie @Goddesen

**Comment by Nubbie** [comment]
The notification works great and looks good :D

**Comment by telk5093** [comment]
ko-KR is applied this.

**Comment by Gymnasiast** [comment]
@Wirlie @J0anJosep @izhangfei @daihakken
