### ISSUE TITLE
STR_6156

### ISSUE THREAD

**Issue by trigger-death** [OpenRCT2/Localisation#1257]
New strings from PR OpenRCT2/OpenRCT2#6471.

```
STR_6156    :Name is reserved
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES
- [x] ja-JP

Notification when new strings arrive:
@Nubbie @Goddesen

**Comment by telk5093** [comment]
``STR_6156    :Name is reserved``

**Comment by Nubbie** [comment]
It hasn't been merged yet
And the string is incorrect, see telk5093's comment

**Comment by Gymnasiast** [comment]
Closing this until the relevant PR is merged.
