### ISSUE TITLE
String 6154+6155

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#1259]
New strings from PR OpenRCT2/OpenRCT2#6438.

```
STR_6154    :It is not recommended to run OpenRCT2 with elevated permissions.
STR_6155    :Neither KDialog nor Zenity are installed. Please install one, or configure from the command line.
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES
- [x] ja-JP

Notification when new strings arrive:
@Nubbie @Goddesen

**Comment by telk5093** [comment]
ko-KR is applied
