### ISSUE TITLE
STR_2866

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/Localisation#1327]
Changed strings from PR OpenRCT2/OpenRCT2#6785.

```
STR_2866    :{WINDOW_COLOUR_2}La Belle Espagnole:   (Robert Vollstedt) Copyright Control
```

Btw, the song has a German name: "Die schöne Spanierin", but I guess we'll use the same name in all Localisations?

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES
- [x] ja-JP
- [x] ar-EG

Notification when new strings arrive:
@Nubbie @Goddesen @octaroot @telk5093

**Comment by Gymnasiast** [comment]
> Btw, the song has a German name: "Die schöne Spanierin", but I guess we'll use the same name in all Localisations?

It's up to the translators to decide which name to use (or to use both names). Whatever localises better.
