### ISSUE TITLE
Strings 6165-6166

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/Localisation#1338]
New strings from PR OpenRCT2/OpenRCT2#6812
```
STR_6165    :Use vertical sync
STR_6166    :{SMALLFONT}{BLACK}Synchronises each frame displayed to the monitor's refresh rate, preventing screen tearing.
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES
- [x] ja-JP
- [x] ar-EG

Notification when new strings arrive:
@Nubbie @Goddesen @octaroot @telk5093

**Comment by LRFLEW** [comment]
Thank you @AaronVanGeffen for making the issue (I was going to, but the PR was merged right as I was falling asleep, and didn't remember right away when I woke up).

The only change that should be needed for en-US is to change `Synchronises` to `Synchronizes` in `STR_6166`.
