### ISSUE TITLE
Fix Scenario name <Utopia Park> and <N. America - Extreme Hawaiian Island>

### ISSUE THREAD

**Issue by qqkookie** [OpenRCT2/Localisation#1531]
This is not new string but  scenario name **tag**  that needs fixing in some language files. There are two scenario  name tags to fix. 

(1) `"<N. America - Extreme Hawaiian Island>"` of RCT2 "Wacky World" exp,
 About line 5294 of language file, the  scenario tag is listed as `"<N America - Extreme Hawaiian Island>"`, not `"<N. America - Extreme Hawaiian Island>"` i.e  "N America ...", not "N. America .... The period mark(.) is missing. Correct one is `"<N. America - Extreme Hawaiian Island>"` with period. But many language files including the base source language file like "en-GB" and "en-US" incorrectly uses `"<N America ..."` without the period. Most languages file that are based on the "en-GB" language file have same error: the scenario name is not translated and not listed as part of Wacky World but listed as "other/ expert scenario".

The  program source "src/openrct2/scinario/ScenarioSources.cpp" uses correct "N. America - Extreme Hawaiian Island" name with period. So all language file should change the tag to "<N. America - Extreme Hawaiian Island>" with period.

(2) `"<Utopia Park>"` in RCT1 "Added attractions" exp.
About line 4798 of language file,  correct line in en-GB : `"<Utopia Park>"`
But some languages ( like fr-FR or ja-JP) list it as `"<Utopia>"`. `"<tag>"`

But, in program source code  ( `src/openrct2/scinario/ScenarioSources.cpp`, line 165 )
The SC_UTOPIA constant is assigned as "Utopia".  The original RCT1/Added Attractions expansion uses the scenario name as "Utopia Park", not "Utopia". So this is fault of program, not language file.

So, most languages that uses  `"<Utopia Park>"` tag will not translated correctly. On the contrary, the French and Japanese that uses *incorrect* tag `"<Utopia>"` will be  translated correctly.  So the "ScenarioSources.cpp" should be fixed to SC_UTOPIA_PARK and "Utopia Park" and the `"<Utopia Park>"` tag should be used in all language files.

How can I fix these? I can make a PR in OpenRCT2/OpenRCT2 for source code change and the base "en-GB" language file. But for other languages, how can I fix them all?  Should I change the all languages file and make a issue a PR for OpenRCT2/Localisation, myself?

**Comment by telk5093** [comment]
As I know, Utopia screnario is already made an alias in source, but scenario file wandering in korea seems that has something different contents against its original scenario files.

**Comment by Gymnasiast** [comment]
Utopia Park appears to be a very odd beast: it shows up as "Utopia Park" in the scenario list of RCT1, but if you start a game, it will show up as "Utopia".

Since we identify scenarios based in the scenario list name, the correct tag should be "Utopia Park". I will change the OpenRCT2 source code accordingly.

**Comment by Gymnasiast** [comment]
Should now be fixed.
