### ISSUE TITLE
Strings 6262–6263, 1777

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/Localisation#1542]
New strings from PR OpenRCT2/OpenRCT2#7848:

```diff
+STR_6262    :Master volume
+STR_6263    :{SMALLFONT}{BLACK}Toggle all sound on/off
```

Note that the second string is used as the tooltip for the master volume checkbox, not the volume slider itself.

The follow string was also amended to remove a colour code:
```diff
-STR_1777    :{WINDOW_COLOUR_2}Ride music
+STR_1777    :Ride music
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES
- [x] ja-JP
- [x] ar-EG
- [x] tr-TR

Notification when new strings arrive:
@Nubbie @Goddesen @octaroot @telk5093 @Omaranwa @danidoedel

**Comment by Wuzzy2** [comment]
As a German translator, I can confirm that de-DE is already done.
