### ISSUE TITLE
String 6264–6265, 2707

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/Localisation#1545]
New strings from PR OpenRCT2/OpenRCT2#7902:

```diff
+STR_6264    :Always use system file browser
+STR_6265    :{SMALLFONT}{BLACK}When enabled, your operating system's file browser will be used instead of OpenRCT2's.
```

The following string has also been changed to match:

```diff
-STR_2707    :Use system dialog window
+STR_2707    :Use system file browser
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES
- [x] ja-JP
- [x] ar-EG
- [x] tr-TR

Notification when new strings arrive:
@Nubbie @Goddesen @octaroot @telk5093 @Omaranwa @danidoedel

**Comment by octaroot** [comment]
@AaronVanGeffen Next time could you please paste the strings without the leading +/- signs? Thanks :-)

**Comment by Goddesen** [comment]
@octaroot @AaronVanGeffen I prefer them myself -- I really like seeing the changes made explicit.

**Comment by Gymnasiast** [comment]
@LPSGizmo @BobbyS38 This also needs translations for Danish and Turkish. There are more new translations. Could you check which ones you need to add to your respective languages.

I have set up notifications for both of you when someone adds a new string.

**Comment by AlarmingEarth** [comment]
https://github.com/OpenRCT2/Localisation/pull/1592
I've added the German (de-DE) translation of these strings.
