### ISSUE TITLE
Quote fix in string 2901

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#1584]
```diff
-STR_2901    :{WINDOW_COLOUR_2}(Samples courtesy of Spectrasonics ”Liquid Grooves”)
+STR_2901    :{WINDOW_COLOUR_2}(Samples courtesy of Spectrasonics “Liquid Grooves”)
```

**Note: this may already have been addressed in your language. If that's the case, please say so. Also, note that you should use the quotes style that belong to your language - e.g. the French translation should use left and right guillemets instead of double quotes.**

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES
- [x] ja-JP
- [x] ar-EG
- [x] da-DK
- [x] tr-TR
- [x] hu-HU

Notification when new strings arrive:
@Nubbie @Goddesen @octaroot @telk5093 @Omaranwa @danidoedel @LPSGizmo @BobbyS38 @frenchiveruti @anon569

**Comment by J0anJosep** [comment]
Already fixed in Catalan.

**Comment by Nubbie** [comment]
sv-SE have applied
