### ISSUE TITLE
Issue with Traditional Chinese

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#160]
STR_3172 should be:
```
STR_3172    :The following object must be selected first: {STRING}
```
Please pay attention, @daihakken . You shouldn't remove parameters. Also, you seem to have based your last version on US English. This is wrong, you should base it on UK English, as is clearly stated in the readme. Here is a link that is always up to date: https://github.com/OpenRCT2/OpenRCT2/blob/develop/data/language/english_uk.txt

**Comment by daihakken** [comment]
I **didn't** remove the parameters, it should be missing from the English (US). I will use the latest revision of English (UK) from now on, thank you for your reminder.

**Comment by Gymnasiast** [comment]
You _did_ remove it, by merging English US into your file: https://github.com/OpenRCT2/Localisation/commit/41ed355d4202215745ddd88a3f7d8461dc885546
