### ISSUE TITLE
Strings 6270-6273

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/Localisation#1610]
New strings from PR OpenRCT2/OpenRCT2#7961.

```
STR_6270    :Terrain Surfaces
STR_6271    :Terrain Edges
STR_6272    :Stations
STR_6273    :Music
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW
- [x] ca-ES
- [x] ja-JP
- [x] ar-EG
- [x] da-DK
- [ ] tr-TR
- [x] hu-HU

Notification when new strings arrive:
@Nubbie @Goddesen @octaroot @telk5093 @Omaranwa @danidoedel @LPSGizmo @BobbyS38 @frenchiveruti @anon569

**Comment by Gymnasiast** [comment]
Closing this as tr-TR is unmaintained.
