### ISSUE TITLE
Removed string 3194

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#1670]
Removed string from PR OpenRCT2/OpenRCT2#8889.

```diff
-STR_3194    :Scenario Description
```

Updated in:
- [x] ar-EG
- [x] ca-ES
- [x] cs-CZ
- [x] da-DK
- [x] de-DE
- [x] en-US
- [x] es-ES
- [x] fr-FR
- [x] hu-HU
- [x] it-IT
- [x] ja-JP
- [x] ko-KR
- [x] nb-NO
- [x] nl-NL
- [x] pt-BR
- [x] sv-SE
- [x] tr-TR
- [x] zh-CN
- [x] zh-TW

Notification when new strings arrive:
@Nubbie @Goddesen @octaroot @telk5093 @Omaranwa @danidoedel @LPSGizmo @BobbyS38 @frenchiveruti @anon569 @JoelTroch

**Comment by JoelTroch** [comment]
@Gymnasiast Please tick "fr-FR" as merged PR #1673 took care of this issue.
