### ISSUE TITLE
Status bars in README file are not visible

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/Localisation#1764]
Go here: https://github.com/OpenRCT2/Localisation

Read the readme. Scroll down all the way to “Language Status”. Below you will find a table. One column is titled “Status Bars”.

To me, this column is empty.

## Analysis

In the source code, I see links in this column. When I try to open the links, I get error 404.

**Comment by Wuzzy2** [comment]
Maybe this can be fixed by replacing “api.openrct2.website” with “api.openrct2.io” in `README.md`. As far I know, openrct2.website is unofficial, but openrct2.io is official.

**Comment by Gymnasiast** [comment]
openrct2.website was official, but at some point we registered the .io domain and abandoned .website.

**Comment by Gymnasiast** [comment]
Unfortunately, progressed.io, which generated these bars, is no longer with us. Since we're not aware of another such service, I have removed the status bars.
