### ISSUE TITLE
Add me to notifications when new strings arrive

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/Localisation#1779]
Hello, I'm Wuzzy and I have translated a couple of strings into German for OpenRCT2 in the past.

I request to be added to the list of notifications in new issues when a new string arrives.

**Comment by AaronVanGeffen** [comment]
You can file a PR to this file to sort this: https://github.com/OpenRCT2/Localisation/blob/master/.github/ISSUE_TEMPLATE.md

(I'd sort it myself, but I'm on vacation and just on mobile.)
