### ISSUE TITLE
String is deleted but not marked as removed

### ISSUE THREAD

**Issue by Lastorder-DC** [OpenRCT2/Localisation#1885]
Strings used from twitch integration removed at #1875 but strings are not marked as deleted.
As a result, translaters may readd strings if their local copy is not up-to-date.
(For example, #1884 readded twitch strings)

It should marked as `<removed string - do not use>`

**Comment by Gymnasiast** [comment]
We used to do that, but we have ultimately decided to just remove them and avoid building up a "collection" of decommissioned strings.
