### ISSUE TITLE
Script to check translation completion

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/Localisation#1900]
I suggest to add a script to check translations:

* Check which strings are missnig
* Display completion %
* Check if ther
* Maybe do other sanity checks (like placeholder mismatch, etc.)

This would help greatly with quality assurance and make it easier to find overlooked strings. The current method of checking everything by hand is very error-prone; I'm betting that a good script will find problems that nobody was aware of. :P

**Comment by Gymnasiast** [comment]
That would be useful indeed. We actually used to have one, but it relied on a service that no longer exists.

**Comment by tupaschoal** [comment]
We have one for objects in [OpenRCT2/objects](https://github.com/OpenRCT2/objects), It should be a lot easier to implement one for this repo, as each language is a single file
