### ISSUE TITLE
New fields requiring translation (Powered Launch)

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/Localisation#20]
STR_1064 and STR_1096 have been modified in UK English these need to be translated across the rest of the languages.

```
-STR_1064    :Powered launch
+STR_1064    :Powered launch (passing station)

-STR_1096    :Powered launch
+STR_1096    :Powered launch (without passing station)
```

**Comment by Gymnasiast** [comment]
Current status:

To be modified:
- French (PR pending)
- German
- Italian
- Swedish
- Spanish
- Polish
- Hungarian

Modified:
- English (UK)
- English (US)
- Dutch
