### ISSUE TITLE
NotADirectoryError running .py file inside workflow.

### ISSUE THREAD

**Issue by frenchiveruti** [OpenRCT2/Localisation#2024]
![imagen](https://user-images.githubusercontent.com/1095997/97802504-b9c0ca80-1c3b-11eb-9e8e-c402b17564ec.png)
Simply put, it ain't working.

![imagen](https://user-images.githubusercontent.com/1095997/97802517-d78e2f80-1c3b-11eb-9548-7450e8f009d8.png)

**Comment by tupaschoal** [comment]
`-m` and `-b` switches expect a directory with the language files, not a file itself. This is shown on the error `NotADirectory`. Try pointing to `data/language` and it should work.

**Comment by frenchiveruti** [comment]
lol now it's complaining about this:
![imagen](https://user-images.githubusercontent.com/1095997/97945955-f0542d80-1d80-11eb-912c-5fbe8bdd502d.png)

**Comment by tupaschoal** [comment]
Seems like you forgot `-m`. You need to provide all three switches, two of them expect directories and one of them a file.

**Comment by frenchiveruti** [comment]
Shit, I thank you for your patience...

**Comment by frenchiveruti** [comment]
All good, it works.
