### ISSUE TITLE
Checker script includes legacy strings?

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/Localisation#2069]
I just noticed the checker script (`.github/workflows/translation_check.py`) complains about missing German strings for TTPIRF02-TTPIRF08, TTRFWD01-TTRFWD08, TTRFGL01-TTRFGL03, AACW33 and ACWWF32.
But if I remember correctly, those strings were recently moved to the objects repo, so they should no longer be relevant, right? I might be wrong, however.

If I am correct, the checker script needs to ignore those strings.

**Comment by Gymnasiast** [comment]
Some object's translations have indeed been moved (e.g. TTRFTL02), but the ones you mentioned have not yet been moved to the objects repo, and thus still need to be in the translation files.

**Comment by Wuzzy2** [comment]
I assume this implies it is planned to move these strings to the objects repo eventually. Right?

**Comment by Gymnasiast** [comment]
In some form: yes. They represent objects that are common enough to warrant translation and/or fixes, but are not made official. They will be among the first to be converted to JSON objects once our object downloader can download them.
