### ISSUE TITLE
Some languages are no longer maintained

### ISSUE THREAD

**Issue by marcinkunert** [OpenRCT2/Localisation#2315]
Some languages currently have >= 200 missing translations. Maintainers could you please add missing translations or point to someone that could do that?

- `ar-EG` - 379 @Omaranwa
- `cz-CZ` - 379 missing - @octaroot
- `hu-HU` - 243 missing - @anon569
- `nb-NO` - 352 missing - @Goddesen
- `tr-TR` - 214 missing - already marked as not maintained, could be removed from new translation checklist template
- `zh-CN` - 204 missing - @izhangfei

**Comment by marcinkunert** [comment]
`zn-CN` is now maintained by @LPR-Michael, but there is no update on the other languages. @Gymnasiast, @tupaschoal what is your opinion on this? Can we mark the languages as "not maintained" and remove it from the new translation issue template?

**Comment by tupaschoal** [comment]
1. I wouldn't add someone to the maintainers list, unless that person agrees or asks for it (let us know @LPR-Michael!). 
2. `tr-TR` is indeed marked as outdated, so I think we should remove it from the template and from the open issues (as it could potentially lead to closing some issues.
3. As for unmaintained translations and inactive contributors, I think we could set some rule that after 6mo or 1y of inactivity if a language, it becomes outdated, if a maintainer, they are removed from the template and list of maintainers. I've compiled the table below and can apply the changes if @Gymnasiast agrees, most that are inactive for over 6mo are also for over 1y:

|Language|Last specific update|>6mo inactivity|>12mo inactivity|
|---|---|---|---|
|ar-EG|Jul 2019|Yes|Yes|
|ca-ES|May 2022|||
|cs-CZ|Oct 2020|Yes|Yes|
|da-DK|Apr 2022|||
|de-DE|Jul 2022|||
|en-US|Not applicable|||
|eo-ZZ|Jul 2022|||
|es-ES|Jul 2022|||
|fi-FI|Jun 2022|||
|fr-FR|Jul 2022|||
|hu-HU|Nov 2021|Yes||
|it-IT|Jun 2022|||
|ja-JP|Oct 2020|Yes|Yes|
|ko-KR|Jul 2022|||
|nb-NO|Aug 2019|Yes|Yes|
|nl-NL|Jul 2022|||
|pl-PL|May 2022|||
|pt-BR|Jul 2022|||
|ru-RU|Aug 2018|Yes|Yes|
|sv-SE|Jan 2022|Yes||
|tr-TR|Dec 2018|Yes|Yes|
|vi-VN|Mar 2021|Yes|Yes|
|zh-CN|Jul 2022|||
|zh-TW|May 2022|||


|Language|Maintainer|Last contribution|>6mo inactivity|>12mo inactivity|
|---|---|---|---|---|
|ar-EG|Omaranwa|Jul 2019|Yes|Yes|
|ca-ES|J0anJosep|May 2022|||
|cs-CZ|octaroot|Oct 2020|Yes|Yes|
|da-DK|LPSGizmo|Apr 2022|||
|de-DE|danidoedel|Sep 2020|Yes|Yes|
|de-DE|Wuzzy2|Aug 2022|||
|eo-ZZ|tellovishous|Jul 2022|||
|eo-ZZ|rzhao271|Jan 2021|Yes|Yes|
|es-ES|dimateos|Jul 2022|||
|fi-FI|groenroos|Jun 2022|||
|fr-FR|rmnvgr|Jul 2022|||
|hu-HU|anon569|Nov 2021|Yes||
|it-IT|LucaRed|Jun 2022|||
|ja-JP|AaronVanGeffen|Oct 2020|Yes|Yes|
|ko-KR|telk5093|Jul 2022|||
|nb-NO|Goddesen|Apr 2017|Yes|Yes|
|nl-NL|Gymnasiast|Jul 2022|||
|pl-PL|marcinkunert|Aug 2022|||
|pt-BR|renansimoes|Jan 2021|Yes|Yes|
|pt-BR|Tupaschoal|Aug 2022|||
|sv-SE|galfisk|Feb 2021|Yes|Yes|
|zh-CN|izhangfei|Dec 2018|Yes|Yes|
|zh-TW|daihakken|May 2022|||

**Comment by Gymnasiast** [comment]
I’m not entirely sure this is a good idea. Case in point: the Arabic translator just returned to catch up.

Instead, I just think we should move to a purpose-built translation system (e.g. Transifex or OpenTTD web translator), either an existing one or one we built ourselves.

**Comment by tupaschoal** [comment]
Ah, that would definitely be better, but more difficult to accomplish. I noticed that the arabic translator had returned while I was typing my comment and updated it, but I think that's a corner case.

**Comment by Gymnasiast** [comment]
Certainly, but leaving a language out of the checkboxes does make it harder to see what needs to be updated, should someone wish to pick it up again.

**Comment by tupaschoal** [comment]
We could keep them on the checkboxes, but close issues as maintained languages are done keeping up? Note that our usage of checkboxes hasn't been too consistent either, I think, so this is already a difficulty for some languages that became outdated, I guess

**Comment by Goddesen** [comment]
`nb-NO` is caught up (though the initial translation is still missing a lot). I'll try to keep on top of new changes.

**Comment by Gymnasiast** [comment]
Considering the long-absent Norwegian translator also came back, I’m definitively _not_ closing old issues or removing them from checkboxes.

**Comment by Goddesen** [comment]
I think that's a good idea hah. I had been kind of paying attention, meaning to get back to this repo. This issue finally spurred me to action, catching up would have been a whole lot less organized without the issues. Lots of context lost.
