### ISSUE TITLE
String STR_2333 [it-IT]

### ISSUE THREAD

**Issue by albertus82** [OpenRCT2/Localisation#2424]
Updated string on PR OpenRCT2/Localisation#2425. Fixed wrong translation.

```
STR_2333    :Effetti sonori
```

Before:

![image](https://user-images.githubusercontent.com/8672431/185758535-d3d6341d-d763-43a6-9a01-9f7c875ea60c.png)

After:

![image](https://user-images.githubusercontent.com/8672431/185758569-7aa5da72-62d5-4322-a2a1-64b82b13a525.png)

Updated in:
- [ ] ar-EG
- [ ] ca-ES
- [ ] cs-CZ
- [ ] da-DK
- [ ] de-DE
- [ ] en-US
- [ ] eo-ZZ
- [ ] es-ES
- [ ] fi-FI
- [ ] fr-FR
- [ ] hu-HU
- [x] it-IT
- [ ] ja-JP
- [ ] ko-KR
- [ ] nb-NO
- [ ] nl-NL
- [ ] pl-PL
- [ ] pt-BR
- [ ] sv-SE
- [ ] tr-TR
- [ ] zh-CN
- [ ] zh-TW

Notification when new strings arrive:
@Omaranwa @J0anJosep @octaroot @LPSGizmo @danidoedel @Wuzzy2 @tellovishous @rzhao271 @anon569 @LucaRed @AaronVanGeffen @telk5093 @Goddesen @Gymnasiast @renansimoes @Tupaschoal @izhangfei @daihakken @marcinkunert @groenroos @dimateos @rmnvgr

**Comment by danidoedel** [comment]
I think the contents of this issue would have been better placed inside the PR. Like this every maintainer got notified for something which is irrelevant for every other language 🙂

**Comment by albertus82** [comment]
Yes, probably this issue is unnecessary as the PR https://github.com/OpenRCT2/Localisation/pull/2425 is self-consistent, so I'm going to move the contents there. Thanks.
