### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by Zhen-Xlogic** [OpenRCT2/Localisation#260]
Hello,

Today i fork the Localisation of ORCT2 to translate it into Greek language.
I start the edits into the english_us.txt file but i notice a litle problem into the client check screenshot:

![encoding_problem](https://cloud.githubusercontent.com/assets/8121624/10345578/6217d6fa-6d33-11e5-95ef-d38529376033.png)

Its seems that the client does not support UTF-8 encoding.

**Comment by Gymnasiast** [comment]
It does support UTF-8 encoding, but the default font lacks glyphs for Greek scripts (and a whole load of other scripts). For such languages, we use TTF fonts like Arial. Just start translating, once your translations are in the files we can add an entry for Greek.

**Comment by daihakken** [comment]
@Gymnasiast 's right. I suggest that you start your translation, and when after sometimes (like at least 25-50% complete), it will be added into the game.

**Comment by Zhen-Xlogic** [comment]
Ok,
I will start the translation and when i have 25% ~ 50% progress of translation, i will do a pull request. :)
