### ISSUE TITLE
Date display broken for some languages

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#27]
Relevant strings are 2736 and 2737.
This is to keep track of languages that still require fixing. Some of them are already fixed.

Broken date display:
- Hungarian*
- Spanish*
- Swedish*

Fixed date display:
- English (UK)
- English (US)
- Polish
- German
- Dutch
- Italian*
- French*

Languages marked with an asterisk ( * ) don't seem to have active translators and require work to be usable. A solution might be to fill untranslated strings below 5120 with their English equivalents (since they exist but are filled with ???) and letting strings from 5120 fall back to the English UK file. That would at least present users with a usable interface.

**Comment by dkessel** [comment]
Using the English equivalents instead of ??? sounds like a good idea.
