### ISSUE TITLE
Typo in action

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/Localisation#2701]
In the automatic action for each PR, there is a typo in the description of "Not needed":
The translation file contains entries that are not in en-GB and should be removed (e.g. STR_9999 **exits** in given language but is not in en-GB)
![image](https://github.com/OpenRCT2/Localisation/assets/15895532/e76774d0-ad9f-4241-9d29-baafbdb6a95d)

**Comment by Sadret** [comment]
That was quick.

**Comment by Gymnasiast** [comment]
I knew where to look ;-)
