### ISSUE TITLE
STR_2386 doesn't show correct month/year in some languages. 

### ISSUE THREAD

**Issue by yanleiberg** [OpenRCT2/Localisation#2866]
For all scenario goal with a guest number requirement and park rating 600 in rct1 and rct2, 
it always displays the deadline to " the end of March, Year 1, with a park rating of at least 600“ in Chinese and Japanese

string id: STR_2386    

1. wrong {monthyear} displaying for the scenario goal string (STR_2386) in zh_cn, zh_tw, ja-JP
2. unnecessary {newline} before number of guest in zh_cn

surprisingly this is correctly displaying in ko-KR.
STR_2387 is correct now in zh_cn, zh_tw, ja-JP, please **don't** modify it. 

How to fix: 
I believe we should simply remove the “{POP16}” before {MONTHYEAR} in STR_2386 but I am not sure for that. 

I am still new to OpenRCT2 even I love RCT1/2, I would like to contribute if possible. 

Here are 2 examples: 

---Forest Frontiers---

  actual display in game: 
	在第1年3月末乐园内至少有
	250游客，并且乐园评分不低于600

  translated from actual display: 
	To have at least 
	250 guests in your park at the end of March, Year 1, with a park rating of at least 600

  correct display should be: 
	在第1年10月末乐园内至少有250游客，并且乐园评分不低于600

---Dynamite Dunes---

  actual display in game: 
	在第1年3月末乐园内至少有
	650游客，并且乐园评分不低于600

  translated from actual display: 
	To have at least 
	650 guests in your park at the end of March, Year 1, with a park rating of at least 600

  correct display should be: 
	在第3年10月末乐园内至少有250游客，并且乐园评分不低于600
	
	
	
![image](https://github.com/OpenRCT2/Localisation/assets/6335952/82659fb8-9386-4d86-bc7e-c3b2a3972cf4)
![image](https://github.com/OpenRCT2/Localisation/assets/6335952/c8a4f63c-02bb-415d-80f6-473c87553cf4)
![image](https://github.com/OpenRCT2/Localisation/assets/6335952/43d318f4-1d9e-4064-be05-6ac374f949f0)

**Comment by mrmagic2020** [comment]
Hi yanleiberg, I had a look into the translation file, and indeed for some reason an extra `{NEWLINE}` is inserted before `{COMMA32}` (where the actual value gets inserted). Removing the `{NEWLINE}` solves the issue. 
https://github.com/OpenRCT2/Localisation/blob/ac99b8ecaa31bf8a086e1868ceadb40c1808e94f/data/language/zh-CN.txt#L1742

However, I'm not sure what is wrong with the `{MONTHYEAR}`. To my understanding, `{POP16}` and `{PUSH16}` are used when you want to alter the order of the value being passed in to make the translation more natural. Since the token `{COMMA32}` appears before `{MONTHYEAR}` in [`en-GB`](https://github.com/OpenRCT2/OpenRCT2/blob/30a9ade6ae394af72200b38587dbd1b9679ed114/data/language/en-GB.txt#L1742C24-L1742C24), here we need to "pop" a token to access the next one, then "push" backwards two times to then fetch the first one.

That being said, the `{MONTHYEAR}` token in `STR_2386` refers to `STR_2736`:
https://github.com/OpenRCT2/Localisation/blob/ac99b8ecaa31bf8a086e1868ceadb40c1808e94f/data/language/zh-CN.txt#L1954
Where the order of the tokens is again altered. Now the issue has become too complex for me to comprehend 😅 Maybe @Gymnasiast could help on this!

<details>
<summary>Stuff I have tried</summary>

1. Restoring token order for `STR_2386`: Everything works fine.
`STR_2386    :{BLACK}园区内至少有{COMMA32}游客，截止{MONTHYEAR}，并且游乐园评分不低于600`
![image](https://github.com/OpenRCT2/Localisation/assets/104749673/37cbaa1f-f9c0-433c-9058-efe0540fffd0)

2. Restoring token order for `STR_2736`: The issue persists.
`STR_2736    :{MONTH}第{COMMA16}年`
![image](https://github.com/OpenRCT2/Localisation/assets/104749673/ae1d72a1-071a-4cdb-bd1c-50b240dd5701)
 - `Month` is March(0), should be October(7)
 - `Year` is correct.

3. Restoring token order for both strings: Everything works fine.
![image](https://github.com/OpenRCT2/Localisation/assets/104749673/58e314fd-df05-4ec2-ab58-d5b7a840c65e)

</details>

**Comment by yanleiberg** [comment]
> 1. Restoring token order for `STR_2386`: Everything works fine.
>    `STR_2386    :{BLACK}园区内至少有{COMMA32}游客，截止{MONTHYEAR}，并且游乐园评分不低于600`
>    ![image](https://private-user-images.githubusercontent.com/104749673/344148658-37cbaa1f-f9c0-433c-9058-efe0540fffd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzY2NzQsIm5iZiI6MTcxOTU3NjM3NCwicGF0aCI6Ii8xMDQ3NDk2NzMvMzQ0MTQ4NjU4LTM3Y2JhYTFmLWY5YzAtNDMzYy05MDU4LWVmZTA1NDBmZmZkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxMjA2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmViMWVkNzkyNTEzYWM5M2RhYjQ5NDBlZTgxYWI1ZjgzODRiMjc5Zjg3NTJmZjZlYTNlYTM3Njg0YmVmNTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7zyR6zbbdprUp0crAEpb1MMRRzzqGxF6ztv1eDJGuAo)
This one seems good, however it doesn't read nature in Chinese.
If we must use {COMMA32} first and then {MONTHYEAR} to fix this issue, I would suggest to modify it like this for zh_cn: 
STR_2386    :{BLACK}园区内至少有{COMMA32}名游客并且游乐园评分不低于600，截止日期为{MONTHYEAR}

result will be:
园区内至少有250名游客并且游乐园评分不低于600，截止日期为第1年10月

> 2. Restoring token order for `STR_2736`: The issue persists.
>    `STR_2736    :{MONTH}第{COMMA16}年`
>    ![image](https://private-user-images.githubusercontent.com/104749673/344146836-ae1d72a1-071a-4cdb-bd1c-50b240dd5701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzY2NzQsIm5iZiI6MTcxOTU3NjM3NCwicGF0aCI6Ii8xMDQ3NDk2NzMvMzQ0MTQ2ODM2LWFlMWQ3MmExLTA3MWEtNGNkYi1iZDFjLTUwYjI0MGRkNTcwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxMjA2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDIyNDgxYjY5YjNhNzc0N2Y0MjZmMmYyNGIxZjMxNTY4MjIxNTExMjcxYzFjNjdmMGYxOTgxNTgxNzc5NmE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0LszhH0ByRTt1OpWmvNDpxSy-C9c1VBzCq12ni2UxLE)
> 
> * `Month` is March(0), should be October(7)
> * `Year` is correct.
> 
This one is wrong indeed. 

> 3. Restoring token order for both strings: Everything works fine.
>    ![image](https://private-user-images.githubusercontent.com/104749673/344147804-58e314fd-df05-4ec2-ab58-d5b7a840c65e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzY2NzQsIm5iZiI6MTcxOTU3NjM3NCwicGF0aCI6Ii8xMDQ3NDk2NzMvMzQ0MTQ3ODA0LTU4ZTMxNGZkLWRmMDUtNGVjMi1hYjU4LWQ1YjdhODQwYzY1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxMjA2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmM4MWRhYjc2Nzk1M2RmODBmNWQ2M2FlMzUzYzNkODNkNzE5MWVhOGEyNmU5NTJhNjU2YjBlZDY1NzAxOWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z-tHHFT5Kvxj_U1pybYnLX7PwXpj-OjoTwZbulGAisk)
This one is partially correct, the month 10 (october) and the year (1 ) is correct, however in Chinese and Japanese, the year should appear before the month, this one is showing month before the year.

**Comment by mrmagic2020** [comment]
> I am also curious where is the character "末" comes from. I did a search on zh-CN.txt but I couldn't find it. This character means "the end" for a month. This character itself isn't containted by the STR_2386 so I assume it is from {MONTHYEAR}, could this be the cause of this issue?
> 
> ![image](https://private-user-images.githubusercontent.com/6335952/344163236-502e054c-a4b1-4402-bc7a-7af22633ffd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1Nzg5NzYsIm5iZiI6MTcxOTU3ODY3NiwicGF0aCI6Ii82MzM1OTUyLzM0NDE2MzIzNi01MDJlMDU0Yy1hNGIxLTQ0MDItYmM3YS03YWYyMjYzM2ZmZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMTI0NDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc0OGUzYWViNTFkY2JlMGJmOGNiNzgzMjhjZTU4NzM5ODczMWU4NmQyNmUxYTJhYmEzMjgwZGNlY2I4NTgyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fEuImaUEoTrlzSpTaYA5pPVNEJBIg2f8OXtZg6syDiA)

That's because this string has been updated since the last release. 
See: https://github.com/OpenRCT2/Localisation/pull/2811/files#diff-5568d548799b97a557080e334d05654ae340853df906921bc3faf05ef7f7b517R1742.

**Comment by yanleiberg** [comment]
Thank you @mrmagic2020 

I have test on my side, yes this character "末" is in the STR_2386 in the file zh-CN.txt. 

I have tested by changing the line 1742 from 
`STR_2386    :{BLACK}在{POP16}{MONTHYEAR}末乐园内至少有{NEWLINE}{PUSH16}{PUSH16}{COMMA32}游客，并且乐园评分不低于600
`
to 
`STR_2386    :{BLACK}在{POP16}{POP16}{MONTHYEAR}末乐园内至少有{PUSH16}{PUSH16}{PUSH16}{COMMA32}游客，并且乐园评分不低于600
`
with one more POP16 and PUSH16, it is correctly displaying the {MONTHYEAR} now. 
Also tested for zh_cn, zh_tw, ja-JP, all working now. with one extra pair of POP16 and PUSH16. and removing {NEWLINE} in zh-CN
![image](https://github.com/OpenRCT2/Localisation/assets/6335952/da0e09a0-f33d-4cb1-84ce-916db1cffd2e)
![image](https://github.com/OpenRCT2/Localisation/assets/6335952/4c5f402b-6d40-40c8-a1bc-248f1da5f7e8)

**Comment by yanleiberg** [comment]
I still don't know the cause of this issue thought, but it works now on my openrct2 😄

**Comment by yanleiberg** [comment]
I would like to do a pull request for this fix, which repo should I fork? 
https://github.com/OpenRCT2/OpenRCT2 
or
https://github.com/OpenRCT2/Localisation

**Comment by yanleiberg** [comment]
> That's because this string has been updated since the last release. See: https://github.com/OpenRCT2/Localisation/pull/2811/files#diff-5568d548799b97a557080e334d05654ae340853df906921bc3faf05ef7f7b517R1742.

Why I cannot see this change in the master branch of https://github.com/OpenRCT2/Localisation?

**Comment by AaronVanGeffen** [comment]
> Why I cannot see this change in the master branch 

The `master` branch reflects the latest release. You'll want to look at the `develop` branch instead, i.e. https://github.com/OpenRCT2/Localisation/blob/develop/data/language/zh-CN.txt

**Comment by yanleiberg** [comment]
oh I got it, the PR 2811 on May-16 is the one without the character "末", and the last release I have on my local was build on May-5 with it. 
Actualy by remove the character "末"，this will leads to a ambiguity of whether is the goal date due on the beginning or the end of a month. I recommend to add it back. 

PR created.

**Comment by telk5093** [comment]
> surprisingly this is correctly displaying in ko-KR.

Yeah, Korean translation did not change the order of ``{COMMA32}`` AND ``{MONTHYEAR}`` to avoid this.

**Comment by yanleiberg** [comment]
> The `master` branch reflects the latest release. You'll want to look at the `develop` branch instead, i.e. https://github.com/OpenRCT2/Localisation/blob/develop/data/language/zh-CN.txt

I got 404 with your link. 
![image](https://github.com/OpenRCT2/Localisation/assets/6335952/36761213-4174-47cd-afd2-d19bc3088a0c)

**Comment by mrmagic2020** [comment]
> > The `master` branch reflects the latest release. You'll want to look at the `develop` branch instead, i.e. https://github.com/OpenRCT2/Localisation/blob/develop/data/language/zh-CN.txt
> 
> I got 404 with your link. ![image](https://private-user-images.githubusercontent.com/6335952/344366411-36761213-4174-47cd-afd2-d19bc3088a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzkyMzUsIm5iZiI6MTcxOTYzODkzNSwicGF0aCI6Ii82MzM1OTUyLzM0NDM2NjQxMS0zNjc2MTIxMy00MTc0LTQ3Y2QtYWZkMi1kMTliYzMwODhhMGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjlUMDUyODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWUxYWZkNzA4MmE4NWIzZWM4ODBmMzY3NWQ5ODBmY2JjYWQ0ZTJkZmVmZTY0ODIzN2RmODI4NjRlM2Q0ZWI0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j8QBHz45vHGHnE25dI8DJPBi_in1eEPZEgU-BA4wDIU)

Should be this one: https://github.com/OpenRCT2/OpenRCT2/blob/develop/data/language/zh-CN.txt

**Comment by Gymnasiast** [comment]
Thank you for finding and fixing this! The root of the problem is that our translation system is rather limited and still employs pushing and popping items from a stack, rather than allowing to specify an order.
