### ISSUE TITLE
New fields requiring translation (Random title music)

### ISSUE THREAD

**Issue by trigger-death** [OpenRCT2/Localisation#31]
STR_5126 has been added to English (UK) and English (US) as "Random title music"

**Comment by Gymnasiast** [comment]
Thanks for the notification. Strictly speaking though, only the UK English translation is maintained in the IntelOrca/OpenRCT2 repo, all other translation, _including_ US English are maintained here.

**Comment by Gymnasiast** [comment]
Reopening this since not every language has strings for it yet. I'll put the missing strings in the other languages when I have time.
