### ISSUE TITLE
Use 'guests' instead of 'peeps' throughout

### ISSUE THREAD

**Issue by dpk** [OpenRCT2/Localisation#324]
Currently in the options and cheats screens there are several places where "peeps" is used (e.g. STR_2684, STR_5165). RCT2's original is "guests", which I don't especially like, but consistent language would aid clarity.

**Comment by Gymnasiast** [comment]
US English has now been changed, a PR for UK English has been opened. Other languages have their own policy and are not likely to use 'peep' anyway.
