### ISSUE TITLE
Languages other than UK English, US English, Dutch, German and Traditional Chinese are not up to date

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#40]
This is a known problem which will only be solved once more languages get translators.

In the meantime, a string will be considered translated when it has been translated in the active languages named in the title of this issue.

**Comment by gdabi** [comment]
I can maintain the spanish language. I'm currently adding the new strings STR_5XXX, translating the game and testing the translation to avoid glitches.

**Comment by Wirlie** [comment]
Please change the tittle of this (If this "information comment" is still used). Spanish translation is already up to date :)

**Comment by Gymnasiast** [comment]
@Wirlie : If you keep that up for a few weeks, I will change it. :)

**Comment by Wirlie** [comment]
this is required? README already shows this: https://github.com/OpenRCT2/Localisation#language-status

**Comment by Gymnasiast** [comment]
I'll use that from now on. It was introduced very recently.
