### ISSUE TITLE
STR_2775 and STR_5177

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#484]
```
STR_2775    :Fullscreen (borderless window)
STR_5177    :Screen mode:
```

**Comment by IntelOrca** [comment]
US still needs updating

**Comment by dlee13** [comment]
I think a diff should be run on UK and US. Then remove the strings that are identical, and leave the strings that are different. That way, when UK is changed, US has its strings changed as well. I don't see the reason for having the duplicates in US when it can fallback on UK.

**Comment by Gymnasiast** [comment]
Indeed. Although I would have to check how it behaves with low IDs.

**Comment by Gymnasiast** [comment]
I have removed strings in US with IDs higher than or equal to 5177, except for those that differ from UK English. It will therefore now show the correct strings.
