### ISSUE TITLE
Localisation - Descriptions for cheats (Discussion)

### ISSUE THREAD

**Issue by Nubbiy** [OpenRCT2/Localisation#489]
Have been talking with people over the community on different servers and also been a bit confused over it myself. 
There are some cheat commands that are slightly confusing for people and adding a description to them won't do any harm more than help people, it's just some extra strings to the English UK localisation file.

For example:
**Unlock all prices** - Set both park and ride prices
**All destructible** - ???
**Reset crash status** - ??? (as when a coaster crashes, it still says CRASHED afterward even if you spam the button)
**Disable Clearance Checks** (Maybe)

Just using the lines in the [Wiki](https://github.com/OpenRCT2/OpenRCT2/wiki/Cheats-Window) (Github url) could be enough to make people understand.

**Comment by IntelOrca** [comment]
Yes, they are not very good descriptions. They should be improved.

**All destructible - ** Some scenarios disable editing of some of the rides already in the park. This cheat lifts the restriction.
**Reset crash status - ** Resets the crash history of a ride, so guests will not complain that its unsafe.

**Comment by Nubbiy** [comment]
Almost no one reads the Wiki tho' when checking out the cheats, would be better to have a description in-game! :l

**Comment by IntelOrca** [comment]
@Nubbiy that is what I meant...

**Comment by Nubbiy** [comment]
Made a pull request about this in OpenRCT2/OpenRCT2 [#3219](https://github.com/OpenRCT2/OpenRCT2/pull/3219)
So I'm closing this topic down
