### ISSUE TITLE
 STR_5665: Toggle Scenery Cluster 

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#523]
```
STR_5665    :Toggle Scenery Cluster
```

**Comment by rvgr** [comment]
I don't find this string in the game, where is it?

**Comment by Gymnasiast** [comment]
It's in the permissions list for multiplayer. It controls whether the player is allowed to use this button:

![scr185](https://cloud.githubusercontent.com/assets/1478678/14410360/f6417e9e-ff2d-11e5-93e4-af433453bc59.png)

**Comment by rvgr** [comment]
Thank you!
