### ISSUE TITLE
STR_5755 wants a string now

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/Localisation#548]
This is to hint server version to the client, when they are incompatible.

https://github.com/OpenRCT2/OpenRCT2/pull/3350

```
STR_5755    :Incorrect Software Version (Server is using {STRING})
```

**Comment by Wirlie** [comment]
For more clarification, this is the field with this change:

    STR_5755    :Incorrect Software Version (Server is using {STRING})
