### ISSUE TITLE
STR_3357, STR_5813 and STR_5814

### ISSUE THREAD

**Issue by danidoedel** [OpenRCT2/Localisation#622]
https://github.com/OpenRCT2/OpenRCT2/commit/fc6a589c3551917da5b5ab744d723c690011338f
https://github.com/OpenRCT2/OpenRCT2/pull/3477

**changed string:**
```
STR_3357    :{WINDOW_COLOUR_2}Are you sure you want to permanently delete {STRING} ?
```

**added strings:**
```
STR_5813    :{OPENQUOTES}{STRING}{ENDQUOTES}
STR_5814    :{WINDOW_COLOUR_1}{OPENQUOTES}{STRING}{ENDQUOTES}
```

**Comment by Nubbie** [comment]
Double checked, and all the languages now have `STR_3357` changed, all maintained languages have `STR_5813 + STR_5814` added to it
This issue maybe should be closed to not confuse people :p
