### ISSUE TITLE
Removed STR_1651 and STR_1652

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#670]
```
STR_1651    :<removed string - do not use>
STR_1652    :<removed string - do not use>
```

**Comment by Nubbie** [comment]
Can do this, still think it's a bit off a beauty off leaving the strings, at least in one file so you can see what was there before

**Comment by Nubbie** [comment]
``
//Two removed inside jokes about Intamin and Phoenix
STR_1651    :<removed string - do not use>
STR_1652    :<removed string - do not use>
``

**Comment by Gymnasiast** [comment]
We have Git for viewing history of the code.

**Comment by Nubbie** [comment]
The 'use ISO 639-1 for language filenames' broke the history as the file changed name

**Comment by Gymnasiast** [comment]
It didn't. That's just a limitation of Github. Git can do a lot more than Github (only a web frontend, really) exposes.

**Comment by Nubbie** [comment]
That's perfect, then you could ignore what I said ^^
Stupid website.. the biggest problem is all the commits it makes, still find the website a bit easier
