### ISSUE TITLE
STR_5861 -> STR_5864 and STR_5666

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/Localisation#674]
NEW STRINGS from PR [#3699](https://github.com/OpenRCT2/OpenRCT2/pull/3699/files):

```
STR_5666    :Passwordless Login
```
```
STR_5861    :Key verification failure.
STR_5862    :Block unknown players.
STR_5863    :{SMALLFONT}{BLACK}Only allow players with known keys to join.
STR_5864    :This server only allows whitelisted players to connect.
```

Updated in:
- [X] en-GB
- [X] en-US
- [x] cs-CZ
- [x] nl-NL
- [X] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [X] sv-SE
- [X] ko-KR
- [x] zh-CN
- [x] zh-TW

_Note: STR_5860 is just temporary and doesn't need to be translated_

**Comment by rvgr** [comment]
What about STR_5666 ("Passwordless Login") also introduced in this PR, should we translate it as well?

**Comment by Nubbie** [comment]
I missed that on the list, absolutely
Thanks for notifying me :)

**Comment by Nubbie** [comment]
@izhangfei @octaroot 
See you two made PR's about this issue but it got changed afterwards as I had missed a string:
```
STR_5666    :Passwordless Login
```
Could you add that too, sorry about the inconvenience, thanks

**Comment by octaroot** [comment]
Why was this closed? `de-DE` PR has not been merged yet and `nl-NL` is also not translated.

**Comment by Gymnasiast** [comment]
@octaroot That was by accident. The Italian PR had 'Fix #xxx' in the title, which automatically closes issues.

**Comment by octaroot** [comment]
Oh :) Sometimes GitHub is too helpful I guess
