### ISSUE TITLE
Suggestion: changing "remove" to "see-through" in view options

### ISSUE THREAD

**Issue by LucaRed** [OpenRCT2/Localisation#748]
I noticed an inconsistency in the wording of the original game. The options to hide land and vertical faces are different from the others: "remove" suggests something permanent (like in "Remove litter"), when in fact it's only a visual aid.

```
STR_0940    :Remove Base Land
STR_0941    :Remove Vertical Faces
STR_0942    :See-Through Rides
STR_0943    :See-Through Scenery
...
STR_2502    :Remove base land toggle
STR_2503    :Remove vertical land toggle
STR_2504    :See-through rides toggle
STR_2505    :See-through scenery toggle
```

I think that something like this would be easier to understand for a new player:

```
STR_0940    :Hide Land
STR_0941    :Hide Vertical Faces
STR_0942    :See-Through Rides
STR_0943    :See-Through Scenery
...
STR_2502    :Hide base land toggle
STR_2503    :Hide vertical land toggle
STR_2504    :See-through rides toggle
STR_2505    :See-through scenery toggle
```

(sorry if this is not the right place to discuss this)

**Comment by Gymnasiast** [comment]
There is a difference: 'Remove Base Land/Vertical faces' makes the base land/vertical faces completely invisible, while the See-through options makes them transparent.
'Hide Base Land' or 'Invisible Base Land' would be more accurate.

**Comment by LucaRed** [comment]
You're right! I've edited the issue.

**Comment by IntelOrca** [comment]
Hide is definitely much better than remove.

**Comment by Gymnasiast** [comment]
@LucaRed Could you open a pull request on [OpenRCT2/OpenRCT2](https://github.com/OpenRCT2/OpenRCT2) to change the four mentioned strings in `en-GB.txt`?
