### ISSUE TITLE
STR_0940, 0941, 2502, 2503

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#749]
Changed strings from PR OpenRCT2/OpenRCT2#3876.

These might already be correct in your translation. Please check if that's the case and if so, please report it here.
```
STR_0940    :Hide Base Land
STR_0941    :Hide Vertical Faces
STR_2502    :Hide base land toggle
STR_2503    :Hide vertical land toggle
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW

**Comment by telk5093** [comment]
ko-KR: No need to translate

**Comment by Nubbie** [comment]
sv-SE.txt - No need to translate

**Comment by Wirlie** [comment]
es-ES: No need to translate

**Comment by octaroot** [comment]
cs-CZ: No need to translate.
