### ISSUE TITLE
STR_5880 & STR_5881

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/Localisation#761]
New strings from PR OpenRCT2/OpenRCT2#3893.

```
STR_5880    :Selected only
STR_5881    :Non-selected only
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [X] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW

**Comment by Gymnasiast** [comment]
Please don't check languages unless they are actually merged.

**Comment by Nubbie** [comment]
@Gymnasiast The only language I check is my own, Swedish

**Comment by Gymnasiast** [comment]
@Nubbie Which was not merged when you checked it.

**Comment by octaroot** [comment]
cs-CZ is merged already, our Czech hearts burn with desire for that little checkbox to be checked :) :P (Also my OCD might have something to do with that).

**Comment by Nubbie** [comment]
@octaroot Presume Gymnasiast missed that as it didn't get linked to the commit :p (Description with the ID or the commit with the ID), fixed anyways :)
