### ISSUE TITLE
Bad string overhang in finance window in the 6th RCT2 scenario, German

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/Localisation#783]
If you play OpenRCT2 in German, there's a bad string overhang in the finance window if you place the 6th RCT2 scenario (something about a bazaar).
It's about the monthly earning of food/drinks/etc. The text for this is longer than the window can contain and goes partly outside the window.

Version: 0.0.4, distributed by Arch Linux.

The string in question is:

    Gewinne des letzten Monats aus Speisen/Getränke und
    - Werbeartikeln:

**Comment by Nubbie** [comment]
Could you move this to [OpenRCT2 issues section](https://github.com/OpenRCT2/OpenRCT2/issues) (We often use this for new strings added to the game :p )

Also, if you speak german, it's something that you could fix too here in: [The String](https://github.com/OpenRCT2/Localisation/blob/master/data/language/de-DE.txt#L2233)

Also, could you provide a screenshot?

**Comment by Wirlie** [comment]
@Nubbie I think that this is the correct place to report this.

@Wuzzy2 You can try to fix this by editing this line, you can try to move `{NEWLINE}` to another position on the string, for example:

    STR_2228    :{WINDOW_COLOUR_2}Gewinne des letzten Monats aus Speisen/{NEWLINE}Getränke und -Werbeartikeln: {BLACK}{CURRENCY}

Also, you can translate [this string](https://github.com/OpenRCT2/OpenRCT2/blob/develop/data/language/en-GB.txt#L2235) from the en-GB file for make a better translation of this string.

**Comment by Nubbie** [comment]
@Wirlie Problem is if it doesn't get fixed and it stays up obscuring the new strings.. and if many add issues here

**Comment by Wirlie** [comment]
And what about #269? :P

**Comment by Nubbie** [comment]
It's a issue that got closed but re-opened for some reason
Have seen more issues in OpenRCT/OpenRCT about language issues

**Comment by Wirlie** [comment]
okay, I won't discuss about this, only I want to help to @Wuzzy2

**Comment by Gymnasiast** [comment]
This belongs here @Nubbie.

**Comment by Nubbie** [comment]
@Gymnasiast Better to move all language related issues here?
