### ISSUE TITLE
STR_5906, STR_5907

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/Localisation#851]
New strings from PR OpenRCT2/OpenRCT2#4146.

```
STR_5906    :Zoom to cursor position
STR_5907    :{SMALLFONT}{BLACK}When enabled, zooming in will centre around the cursor, as opposed to the screen centre.
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW

**Comment by Nubbie** [comment]
@AaronVanGeffen @Gymnasiast You have added two pluses when you copied the text

**Comment by AaronVanGeffen** [comment]
@Nubbie That's just `diff` output. They aren't in the language files themselves, fortunately.

**Comment by Nubbie** [comment]
@AaronVanGeffen Indeed, but when I copy the whole text inside the code brackets, they slink in the translated document

**Comment by Nubbie** [comment]
PR #858 applied for this issue too (SE-sv)
