### ISSUE TITLE
Strings 5920-5921

### ISSUE THREAD

**Issue by octaroot** [OpenRCT2/Localisation#903]
New strings from PR OpenRCT2/OpenRCT2#4302.

```
STR_5920    :Render weather effects
STR_5921    :{SMALLFONT}{BLACK}If enabled, rain and gloomy colours will be rendered during storms.
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW

**Comment by Nubbie** [comment]
@Goddesen
