### ISSUE TITLE
String 5879 (OpenGL labelled experimental)

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/Localisation#935]
Changed string from PR OpenRCT2/OpenRCT2#4716.

```
STR_5879    :OpenGL (experimental)
```

Updated in:
- [x] en-US
- [x] cs-CZ
- [x] nl-NL
- [x] fr-FR
- [x] de-DE
- [x] pt-BR
- [x] es-ES
- [x] it-IT
- [x] sv-SE
- [x] nb-NO
- [x] ko-KR
- [x] zh-CN
- [x] zh-TW

**Comment by Nubbie** [comment]
[ sv-SE have applied ](https://github.com/OpenRCT2/Localisation/commit/cac4820f8f8e36220e62b696474c9bfbdc0928d6)
