### ISSUE TITLE
ISSUE: Language status checker

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/Localisation#972]
This is a issue created just specifically for the language checker, **no strings to translate here**

- The language checker looks through en-US which makes it give out a false reading off 79% strings being present. The language should be ignored by the language checker as we only add strings that really differ from the checker.
The line to change for correcting this; https://github.com/OpenRCT2/Localisation/blob/master/check.ps1#L42
 
- ~~The language changer's API on the OpenRCT2 website gives out a json instead off svg #754~~
 
- Add length/shift scale to the bars (make it easier to read) ([if we're using these bars of course](https://github.com/fehmicansaglam/progressed.io))
Read more about scale here; https://github.com/fehmicansaglam/progressed.io
![examplefwa](https://cloud.githubusercontent.com/assets/17282384/22487343/49627538-e80d-11e6-9238-6e665f91b50f.png)
**One of these should help out, would suggest length to "kill two birds with one stone"**
 
- Clean up the language files and comment out the files for more accurate results 
- [ ] cs-CZ
- [ ] de-DE
- [ ] en-US (Should be ignored)
- [ ] es-ES
- [ ] fi-FI
- [ ] fr-FR
- [ ] hu-HU
- [ ] it-IT
- [ ] ja-JP
- [ ] ko-KR
- [ ] nb-NO
- [ ] nl-NK
- [ ] pl-PL
- [ ] pt-BR
- [ ] ru-RU
- [ ] sv-SE
- [ ] zh-CN
- [ ] zh-TW

**Comment by IntelOrca** [comment]
I have fixed the API
